---
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 83:80
    environment:
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=${PUSH_INSTALLATION_ID}
      - PUSH_INSTALLATION_KEY=${PUSH_INSTALLATION_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/vaultwarden/:/data/
    networks:
      database: