services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: timothyjmiller/cloudflare-ddns:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/cloudflare-ddns/config.json:/config.json
    network_mode: "host"