services:
  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.20.2
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - 9443:9443
    environment:
      - TZ=$TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKERDIR/appdata/portainer/data:/data
    networks:
      - rpi4b-network