---
# Requires a PostgresSQL server
services:
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      SEMAPHORE_DB_USER: ${USER}
      SEMAPHORE_DB_PASS: '${SEMAPHORE_DB_PASS}'
      SEMAPHORE_DB_HOST: postgres # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 5432 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: postgres # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: '${SEMAPHORE_ADMIN_PASSWORD}'
      SEMAPHORE_ADMIN_NAME: Administrator
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: '${SEMAPHORE_ACCESS_KEY_ENCRYPTION}'
      ANSIBLE_HOST_KEY_CHECKING: false
      ANSIBLE_PYTHON_INTERPRETER: auto_silent
      TZ: ${TZ}
    volumes: 
      - $DOCKERDIR/semaphore:/etc/semaphore
    networks:
      - database