---
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: '${EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${POSTGRES_PASSWORD}'
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: '${PGADMIN_CONFIG_AUTHENTICATION_SOURCES}'
      PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: '${PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER}'
      PGADMIN_CONFIG_OAUTH2_CONFIG: '${PGADMIN_CONFIG_OAUTH2_CONFIG}'
      TZ: '${TZ}'
    volumes: 
      - $DOCKERDIR/pgadmin:/var/lib/pgadmin
    networks:
      - database