---
services:
  pve-exporter:
    container_name: pve-exporter
    image: prompve/prometheus-pve-exporter
    restart: unless-stopped
    ports:
      - "9221:9221"
    volumes:
      - $DOCKERDIR/pve/pve.yml:/etc/prometheus/pve.yml
    networks: 
      - monitoring