---
services:
  # Portainer - WebUI for Containers
  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 9001:9001
    environment:
      - TZ=$TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rslave