---
services:
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - $DOCKERDIR/appdata/lidarr/config:/config
      - /mnt/multimedia:/multimedia
      - /mnt/downloads:/downloads
    networks:
      - media
