---
services: 
  cadvisor: 
    container_name: cadvisor 
    image: gcr.io/cadvisor/cadvisor:latest 
    user: "0"
    restart: unless-stopped 
    ports: 
      - 8080:8080 
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    networks: 
      - monitoring
      - database