---
services: 
  graphite-exporter: 
    container_name: graphite-exporter 
    image: prom/graphite-exporter:latest 
    user: "0"
    restart: unless-stopped 
    command:
      - '--graphite.mapping-config=/tmp/graphite_mapping.conf'
    ports: 
      - 9108:9108
      - 9109:9109
      - 9109:9109/udp
    volumes: 
      - $DOCKERDIR/graphite-exporter/graphite_mapping.conf:/tmp/graphite_mapping.conf
    networks: 
      - monitoring