---
services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/npm/data:/data
      - $DOCKERDIR/npm/letsencrypt:/etc/letsencrypt
    networks:
      - networking